#!/usr/bin/env bash
# bash script to install nginx and set up custom headers
sudo apt-get -y install nginx
sudo sed -i "40i \ \t add_header X-Served-By \$hostname;" /etc/nginx/sites-enabled/default
sudo service nginx start
