#!/usr/bin/env bash
#Bash script that display To infinity and beyond indefinitely.

trap "echo I am invincible!!!" SIGTERM
while true
do
  echo "To infinity and beyond"
  sleep 2
  echo "I am invincible!!!" 
done
