#!/usr/bin/env bash
#The script is displaying "Best School" 10 times
j=0
while [ $j != 10 ]
do
  if [ $j = 3 ]
  then
    echo "bad luck"
  elif [ $j = 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  j=$(( j + 1 ))
done