#!/usr/bin/env bash
#script that runs nginx as user nginx
sed -i "li user nginx;" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
chmod 644 /etc/nginx/nginx.conf
pkill -f apache2
service apache2 stop
sudo -u nginx service nginx restart
